version: '3'
services:
  web:
    build: .
    container_name: mvc_web
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
    links:
      - db
    depends_on:
      - db
    networks:
      static-network:
        ipv4_address: 18.0.5.2
  db:
    image: mariadb
    container_name: mvc_db
    environment:
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - '3306:3306'
    networks:
      static-network:
        ipv4_address: 18.0.5.3
networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 18.0.5.0/16
